name: ci
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - name: Install uv
        run: pipx install uv
      - name: Install package (dev)
        run: uv pip install -e ".[dev]"
      - name: Run tests
        run: uv run pytest --cov=skewsentry
      - name: Build wheels
        run: uv run python -m build

